-- ************************************************************************************
-- This script populates the breweries table with sample data (brewer_id must exist)
-- ************************************************************************************
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Brew Detroit' , 2, '1401 Abbott St', 'Detroit', 'Michigan', 48216, 'http://www.brewdetroit.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Detroit Beer Co' , 2, '1529 Broadway St Ste 100', 'Detroit', 'Michigan', 48226, 'http://www.detroitbeerco.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Brewery Faisan' , 3, '1087 Beaufait St', 'Detroit', 'Michigan', 48207, 'http://www.breweryfaisan.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('American Badass Beer' , 4, '1401 Abbott St Corktown', 'Detroit', 'Michigan', 48216, 'http://www.americanbadassbeer.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Atwater Brewing Co' , 5, '237 Joseph Campau St', 'Detroit', 'Michigan', 48207, 'http://www.atwaterbeer.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Batch Brewing Co' , 3, '1400 Porter St', 'Detroit', 'Michigan', 48216, 'http://www.BatchBrewingCompany.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Vivios Food' , 2, '2460 Market Street ', 'Detroit', 'Michigan', 48207, 'http://www.viviosdetroit.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Eastern Market Brewing Company' , 3, '2515 Riopelle St', 'Detroit', 'Michigan', 48207, 'http://www.easternmarket.beer');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Motor City Brewing Works' , 4, '470 W Canfield St', 'Detroit', 'Michigan', 48201, 'http://www.motorcitybeer.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Traffic Jam and Snug' , 2, '4268 2nd Ave', 'Detroit', 'Michigan', 48201, 'http://www.trafficjamdetroit.com');

INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Nano Brew Cleveland' , 3, '1859 W 25th St', 'Cleveland', 'Ohio',44113, 'http://www.nanobrewcleveland.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('The Cleveland Brewery' , 2, '777 E 185th St', 'Cleveland', 'Ohio', 44119, 'http://Www.facebook.com/216brew');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Hofbrauhaus Cleveland / Cincinatti Restaurant Group' , 2, '1550 Chester Ave', 'Cleveland', 'Ohio', 44114, 'http://www.hofbrauhauscleveland.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Hansa Brewery' , 3, '2717 Lorain Ave', 'Cleveland', 'Ohio', '44113', 'http://www.hansabrewery.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Bookhouse Brewing, LLC.' , 4, '1512 W 25th St', 'Cleveland', 'Ohio', '44113', 'http://www.bookhouse.beer');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Boss Dog Brewing' , 4, '2179 Lee Rd', 'Cleveland', 'Ohio', '44118', 'http://www.bossdogbrewing.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Brick and Barrel' , 2, '1844 Columbus Rd', 'Cleveland', 'Ohio', '44113', 'http://www.brickandbarrelbrewing.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Earlybird Brewing Company' , 2, '737 Bolivar Rd Ste 4100', 'Cleveland', 'Ohio', '44115', 'http://www.earlybirdbrewing.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Forest City Brewery' , 3, '2135 Columbus Rd Ste A', 'Cleveland', 'Ohio', '44113', 'http://www.forestcitybrewery.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Masthead Brewing Co' , 4, '1261 Superior Ave E', 'Cleveland', 'Ohio', '44113', 'http://www.mastheadbrewingco.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Platform Beer Co' , 4, '4125 Lorain Ave','Cleveland', 'Ohio', '44113', 'http://platformbeer.co');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Saucy Brew Works' , 3, '2885 Detroit Ave','Cleveland', 'Ohio', '44113', 'http://www.saucybrewworks.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('The Jolly Scholar' , 2, '11111 Euclid Ave','Cleveland', 'Ohio', '44106', 'http://www.thejollyscholar.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Working Class Brewery' , 3, '17448 Lorain Ave','Cleveland', 'Ohio', '44111', 'http://www.workingclassbrewery.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Collision Bend Brewing Co' , 4, '1250 Old River Rd', 'Cleveland', 'Ohio', '44113', 'http://www.collisionbendbrewery.com');

INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Hofbrauhaus Pittsburgh' , 3, '2705 S Water St', 'Pittsburgh', 'Pennsylvania', '15203', 'http://www.hofbrauhauspittsburgh.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Pittsburgh Brewing Co' , 2, '3340 Liberty Ave', 'Pittsburgh', 'Pennsylvania', '15201', 'http://www.pittsburghbrewing.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Couch Brewery' , 2, '1351 Washington Blvd', 'Pittsburgh', 'Pennsylvania', '15206', 'http://www.couchbrewery.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Roundabout Brewery' , 3, '4901 Butler St', 'Pittsburgh', 'Pennsylvania', '15201', 'http://roundaboutbeer.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Allegheny City Brewing' , 4, '507 Foreland St', 'Pittsburgh', 'Pennsylvania', '15212', 'http://www.alleghenycitybrewing.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Cinderlands Beer Co.' , 4, '3705 Butler St', 'Pittsburgh', 'Pennsylvania', '15201', 'http://www.cinderlands.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Dancing Gnome Beer' , 4, '925 Main Std', 'Pittsburgh', 'Pennsylvania', '15215', 'http://www.dancinggnomebeer.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Hitchhiker Brewing Co.' , 2, '190 Castle Shannon Blvd', 'Pittsburgh', 'Pennsylvania', '15228', 'http://www.hitchhikerbrewing.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Pennsylvania Brewing Co' , 3, '800 Vinial St', 'Pittsburgh', 'Pennsylvania', '15212', 'http://www.pennbrew.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Spoonwood Brewing Company' , 4, '5981 Baptist Rd', 'Pittsburgh', 'Pennsylvania', '15236', 'http://www.spoonwoodbrewing.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('East End Brewing Co' , 3, '147 Julius St', 'Pittsburgh', 'Pennsylvania', '15206', 'http://www.eastendbrewing.com');

