-- ************************************************************************************
-- This script populates the breweries table with sample data (brewer_id must exist)
-- ************************************************************************************

INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Brew Detroit' , 1, '1401 Abbott St', 'Detroit', 'Michigan', 48216, 'http://www.brewdetroit.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Detroit Beer Co' , 1, '1529 Broadway St Ste 100', 'Detroit', 'Michigan', 48226, 'http://www.detroitbeerco.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Brewery Faisan' , 1, '1087 Beaufait St', 'Detroit', 'Michigan', 48207, 'http://www.breweryfaisan.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('American Badass Beer' , 1, '1401 Abbott St Corktown', 'Detroit', 'Michigan', 48216, 'http://www.americanbadassbeer.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Atwater Brewing Co' , 1, '237 Joseph Campau St', 'Detroit', 'Michigan', 48207, 'http://www.atwaterbeer.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Batch Brewing Co' , 1, '1400 Porter St', 'Detroit', 'Michigan', 48216, 'http://www.BatchBrewingCompany.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Vivios Food' , 1, '2460 Market Street ', 'Detroit', 'Michigan', 48207, 'http://www.viviosdetroit.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Eastern Market Brewing Company' , 1, '2515 Riopelle St', 'Detroit', 'Michigan', 48207, 'http://www.easternmarket.beer');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Motor City Brewing Works' , 1, '470 W Canfield St', 'Detroit', 'Michigan', 48201, 'http://www.motorcitybeer.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Traffic Jam and Snug' , 1, '4268 2nd Ave', 'Detroit', 'Michigan', 48201, 'http://www.trafficjamdetroit.com');

INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Nano Brew Cleveland' , 1, '1859 W 25th St', 'Cleveland', 'Ohio',44113, 'http://www.nanobrewcleveland.com');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('The Cleveland Brewery' , 1, '777 E 185th St', 'Cleveland', 'Ohio', 44119, 'http://Www.facebook.com/216brew');
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('Hofbrauhaus Cleveland / Cincinatti Restaurant Group' , 1, '1550 Chester Ave', 'Cleveland', 'Ohio', 44114, 'http://www.hofbrauhauscleveland.com')
INSERT INTO breweries (brewery_name, brewer_id, brewery_street_address, brewery_city, brewery_state, brewery_zip, brewery_website) VALUES ('null' , 1, 'null', 'null', 'null', 'null', 'null')